version: '3.5'

services:
  privategpt:
    build: .
    image: skynet
    volumes:
      - ./data/db:/app/db
      - ./data/models:/app/models
      - ./data/source_documents:/app/source_documents
      - ./data/torch:/root/.cache/torch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
